# Generated by Django 5.0.7 on 2024-09-21 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revoltUK', '0002_category_alter_legislation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votingsession',
            name='duration',
        ),
        migrations.AddField(
            model_name='votingsession',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 16, 18, 12, 476305, tzinfo=datetime.timezone.utc)),
        ),
    ]
