# Generated by Django 5.0.7 on 2024-09-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revoltUK', '0004_alter_votingsession_end_time_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
    ]
