# Generated by Django 5.0.7 on 2024-09-22 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revoltUK', '0005_alter_vote_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='voting_session',
            new_name='session',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingsession',
            name='votes',
            field=models.ManyToManyField(related_name='votes', through='revoltUK.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_option',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voted_at',
        ),
    ]
